version: "3"
services: 
  parser_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: parser
      POSTGRES_USER: parser
      POSTGRES_PASSWORD: parser
